algo = input('Digite algo: ')
print('A variavel é alfanumérica? ', algo.isalnum())
print('A variavel é alfabética? ', algo.isalpha())
print('A variavel é fomrada por decimais? ', algo.isdecimal())
print('A variavel é formada apenas por digitos? ', algo.isdigit())
print('A variavel é um string identificador? ', algo.isidentifier())
print('A variavel está em minusculo? ', algo.islower())
print('A variavel é numérica? ', algo.isnumeric())
print('A variavel é imprimivel? ', algo.isprintable())
print('A variável e formada por espaços? ', algo.isspace())
print('A variável é um titulo? ', algo.istitle())
print('A variável está em maiúsculo? ', algo.isupper())
