nome = str(input('Digite seu nome completo: ')).strip()
print('Seu nome em maiúsculo é: {}'.format(nome.upper()))
print('Seu nome em minúscilo é: {}'.format(nome.lower()))
print('Seu nome ao todo tem: {} letras'.format(len(nome) - nome.count(' ')))
pnome = nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(pnome[0], len(pnome[0])))